#!/usr/bin/env bash

clear
INSTALAR_APT=(
  sshpass
)

printf "\n\e[1;92mScript De SSH ONU\n"
printf "\e[1;92mCriador: Danilo Dos Santos\n"
printf "\e[1;92mAtualizado Em: 30/03/2022\n"
printf "\e[1;92mTestado Em Bash[Linux Mint]\n\n"
printf "\e[1;92m----------Conexão SSH STA/EXP/JNG----------\n"

if ! ping -c 1 8.8.8.8 -q &> /dev/null; then
  printf "\e[1;91m[ERRO] - Sem Conexão Com A Internet, Verifique E Tente Novamente\n"
 exit 1
else
  printf "\e[1;92m[INFO] - Conexão Com Internet Estabelecida, Prosseguindo...\n"
fi
for programas in ${INSTALAR_APT[@]}; do
  if  ! dpkg -l | grep -q $programas; then
  printf "\e[1;91m[ERRO] - Necessário O $programas Para Funcionar, Iniciando Instalação\n"
  printf "\e[1;92m[INFO] - Insira Sua Senha De Administrador Do Linux\n\n"
  sudo apt install $programas -y &> /dev/null;
  printf "\e[1;92m[INFO] - O $programas Esta Devidamente Instalado Prosseguindo...\n\n"
else printf "\e[1;92m[INFO] - O $programas Esta Devidamente Instalado Prosseguindo...\n\n"
fi
done

printf "\e[1;92mDigite Seu Nome De Usuário:\n"
read nome
printf "\e[1;92mDigite Sua Senha De Acesso:\n"
read senha &> /dev/null
sshpass -p "$senha" ssh $nome@10.253.254.14

